name: Build and deploy WebAPI to Azure Web App

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up .NET Core for WebAPI
      - name: Set up .NET Core for WebAPI
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'  # Use the version your WebAPI is built with
          include-prerelease: true

      # Build the WebAPI
      - name: Build WebAPI with dotnet
        run: |
          cd WebAPI
          dotnet build --configuration Release

      # Publish the WebAPI
      - name: Publish WebAPI
        run: |
          cd WebAPI
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      # Upload WebAPI artifact
      - name: Upload WebAPI artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapi-artifact
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy_webapi:
    runs-on: windows-latest
    needs: build_and_deploy
    environment:
      name: 'Production'
      url: ${{ steps.deploy-webapi.outputs.webapp-url }}

    steps:
      - name: Download WebAPI artifact
        uses: actions/download-artifact@v3
        with:
          name: webapi-artifact

      - name: Deploy WebAPI to Azure Web App
        id: deploy-webapi
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ProperlyManageMentAPi'  # Your Azure Web API App name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CBF87B73E82346BB895E83F805AD367E }}  # Secret for your publish profile
          package: .
